FROM centos:latest
MAINTAINER kapilyadavky99@gmail.com
RUN yum install httpd git -y
RUN git clone https://github.com/Kapilyadav06/CI-CD-WEB-PAGE-.git /var/www/html
WORKDIR /var/www/html
CMD ["/usr/sbin/httpd","-D","FOREGROUND"]
EXPOSE 80